<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='web/css/bootstrap.min.css' rel='stylesheet' type='text/css'>
        <link href='web/js/DataTables-1.10.10/media/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'>
        <link href='web/css/style.css' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <header>
            <h1>Post-It</h1>
            <div>My first API</div>
        </header>

        <div class="container">
            <div id="action">
                <a href="#addPostitModal" rel="leanModal" class="btn btn-default" style="text-decoration:none; ">Ajouter</a>
            </div>
            <br/>

            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Rechercher
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            <nav id="navbar-example" class="navbar navbar-default navbar-static">
                                <div class="container-fluid">
                                    <div class="navbar-header">
                                        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-example-js-navbar-collapse">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button> <a class="navbar-brand" href="#">Trie par :</a>
                                    </div>
                                    <div class="collapse navbar-collapse bs-example-js-navbar-collapse">
                                        <ul class="nav navbar-nav">
                                            <li class="dropdown">
                                                <a id="drop1" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Titre <span class="caret"></span> </a>
                                                <ul class="dropdown-menu" aria-labelledby="drop1">
                                                    <li><a href="#" class="filterPostit" role="title" rel="asc">Croissant</a></li>
                                                    <li><a href="#" class="filterPostit" role="title" rel="desc">Décroissant</a></li>
                                                </ul>
                                            </li>
                                            <li class="dropdown">
                                                <a id="drop2" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Couleur <span class="caret"></span> </a>
                                                <ul class="dropdown-menu" aria-labelledby="drop2">
                                                    <li><a href="#" class="filterPostit" role="color" rel="asc">Croissant</a></li>
                                                    <li><a href="#" class="filterPostit" role="color" rel="desc">Décroissant</a></li>
                                                </ul>
                                            </li>
                                            <li class="dropdown">
                                                <a id="drop3" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Date <span class="caret"></span> </a>
                                                <ul class="dropdown-menu" aria-labelledby="drop3">
                                                    <li><a href="#" class="filterPostit" role="date" rel="asc">Croissant</a></li>
                                                    <li><a href="#" class="filterPostit" role="date" rel="desc">Décroissant</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                        <ul class="nav navbar-nav navbar-right">
                                            <form id="searchForm" name="searchForm">
                                                <input type="search" name="searchPostit" id="searchPostit" results="5">
                                            </form>
                                        </ul>
                                    </div>
                                </div>
                            </nav>

                            <form name="searchPostitForm" id="searchPostitForm" method="GET" >

                            </form>
                        </div>
                    </div>
                </div>
            </div>


            <div id="datable" >
                <table id="tab_postit" class="display" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Title</th>
                            <th>Content</th>
                            <th>Color</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Content</th>
                        <th>Color</th>
                        <th>Date</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <footer>

        </footer>
        <!-- MODALS -->
        <div id="addPostitModal" style="display:none;">
            <h3>Nouveau Post-It</h3>
            <form id="addPostitForm" name="addPostitForm" class="postitForm" method="post" action="index.html">
                <label for="title">Titre:</label>
                <input type="text" name="title" id="title" class="txtfield" tabindex="1">

                <label for="content">Contenu:</label>
                <input type="text" name="content" id="content" class="txtfield" tabindex="2">

                <label for="color">Couleur:</label>
                <select name="color" id="color" class="txtfield" tabindex="3">
                    <option value="1" style="background-color: blue">Blue</option>
                    <option value="2" style="background-color: green">Green</option>
                    <option value="3" style="background-color: red">Red</option>
                    <option value="4" style="background-color: yellow">Yellow</option>
                </select>

                <div class="center"><input type="submit" name="addbtn" id="addbtn" class="flatbtn-blu hidemodal" value="Ajouter" tabindex="3"></div>
            </form>
        </div>
        <a href="#updPostitModal" rel="leanModal" id="trigger_upd" style=" "></a>
        <div id="updPostitModal" style="display:none;">
            <h3>Mise à jour Post-It</h3>
            <form id="updPostitForm" name="updPostitForm" class="postitForm" method="post" action="index.html">
                <input type="hidden" name="id" id="id">
                <label for="title">Titre:</label>
                <input type="text" name="title" id="title" class="txtfield" tabindex="1">

                <label for="content">Contenu:</label>
                <input type="text" name="content" id="content" class="txtfield" tabindex="2">

                <label for="color">Couleur:</label>
                <select name="color" id="color" class="txtfield" tabindex="3">
                    <option value="1" style="background-color: blue">Blue</option>
                    <option value="2" style="background-color: green">Green</option>
                    <option value="3" style="background-color: red">Red</option>
                    <option value="4" style="background-color: yellow">Yellow</option>
                </select>

                <div class="center"><input type="submit" name="updbtn" id="updbtn" class="flatbtn-blu hidemodal" value="Mettre à Jour" tabindex="4"></div>
                <div class="center" style="margin-top: 5%;"><input type="button" name="dltbtn" id="dltbtn" class="flatbtn-blu hidemodal" value="Supprimer" tabindex="5"></div>
            </form>
        </div>
        <div id="lean_overlay"></div>
        <!-- MODALS -->

        <!-- SCRIPTS JS -->
        <script src="web/js/jquery-2.2.0.min.js"></script>
        <script src="web/js/bootstrap.min.js"></script>
        <script src="web/js/DataTables-1.10.10/media/js/jquery.dataTables.min.js"></script>
        <script src="web/js/jquery.leanModal.min.js"></script>
        <script src="web/js/main.js"></script>
        <!-- SCRIPTS JS -->

    </body>
</html>
